package com.wtf.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LEVEL.
 */
public class Level {

	private Long id;
	/** Not-null value. */
	private String name;
	private int maxScore;

	public Level() {
	}

	public Level(Long id) {
		this.id = id;
	}

	public Level(Long id, String name, int maxScore) {
		this.id = id;
		this.name = name;
		this.maxScore = maxScore;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/** Not-null value. */
	public String getName() {
		return name;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setName(String name) {
		this.name = name;
	}

	public int getMaxScore() {
		return maxScore;
	}

	public void setMaxScore(int maxScore) {
		this.maxScore = maxScore;
	}

}
