package com.wtf.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAYER.
 */
public class Player {

	private Long id;
	/** Not-null value. */
	private String username;
	private int idDevice;

	public Player() {
	}

	public Player(Long id) {
		this.id = id;
	}

	public Player(Long id, String username, int idDevice) {
		this.id = id;
		this.username = username;
		this.idDevice = idDevice;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/** Not-null value. */
	public String getUsername() {
		return username;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	public int getIdDevice() {
		return idDevice;
	}

	public void setIdDevice(int idDevice) {
		this.idDevice = idDevice;
	}

}
