package com.wtf.models;

import java.util.List;

import com.wtf.dao.DaoSession;
import com.wtf.dao.LevelDao;
import com.wtf.dao.LevelPlayerDao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LEVEL.
 */
public class Level {

    private Long id;
    private Integer maxScore;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LevelDao myDao;

    private List<LevelPlayer> levelPlayerList;

    public Level() {
    	
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, Integer maxScore) {
        this.id = id;
        this.maxScore = maxScore;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLevelDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMaxScore() {
        return maxScore;
    }

    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<LevelPlayer> getLevelPlayerList() {
        if (levelPlayerList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LevelPlayerDao targetDao = daoSession.getLevelPlayerDao();
            List<LevelPlayer> levelPlayerListNew = targetDao._queryLevel_LevelPlayerList(id);
            synchronized (this) {
                if(levelPlayerList == null) {
                    levelPlayerList = levelPlayerListNew;
                }
            }
        }
        return levelPlayerList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetLevelPlayerList() {
        levelPlayerList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
