package com.wtf.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.wtf.models.Level;
import com.wtf.models.Player;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig playerDaoConfig;
	private final DaoConfig levelDaoConfig;

	private final PlayerDao playerDao;
	private final LevelDao levelDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		playerDaoConfig = daoConfigMap.get(PlayerDao.class).clone();
		playerDaoConfig.initIdentityScope(type);

		levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
		levelDaoConfig.initIdentityScope(type);

		playerDao = new PlayerDao(playerDaoConfig, this);
		levelDao = new LevelDao(levelDaoConfig, this);

		registerDao(Player.class, playerDao);
		registerDao(Level.class, levelDao);
	}

	public void clear() {
		playerDaoConfig.getIdentityScope().clear();
		levelDaoConfig.getIdentityScope().clear();
	}

	public PlayerDao getPlayerDao() {
		return playerDao;
	}

	public LevelDao getLevelDao() {
		return levelDao;
	}

}
